package.json, sonar-project.properties, src/test/routes/home.ts, src/test/unit/controller/HomeController.test.ts
=> feat: Updated sonar project to exclude some files

package.json, yarn.lock
* Mandatory upgrade for plat-ops to upgrade clusters
```
[ ] Yes
[X] No
```
=> upgraded property volumes version

charts/et-sya/Chart.yaml
=> feat: upgraded node-js chart

src/main/modules/i18next/index.ts, src/test/routes/address-details.test.ts, src/test/routes/mutiple-respondent-check.test.ts, src/test/routes/return-to-existing.test.ts, src/test/routes/single-or-multiple-claim.test.ts, src/test/routes/telephone-number.test.ts, src/test/unit/controller/AcasMultipleController.test.ts, src/test/unit/controller/StepsToMakingYourClaimController.test.ts, src/test/unit/controller/TelNumberController.test.ts, src/test/unit/controller/UpdatePreferenceController.test.ts, yarn.lock
Fixing failing routes tests
```
[ ] Yes
[x ] No
```
=> Fix failing routes tests

src/test/functional/features/homepage.js
JIRA link
[RET-1089](https://tools.hmcts.net/jira/browse/RET-1089)
Functional tests for ET frontend
[ ] Yes
[X] No
=> added more pages to the functional tests journey

src/test/functional/features/homepage.js
https://tools.hmcts.net/jira/browse/RET-1014
Added test automation to ensure the cache worked as intended
refactor automation to rely on waiting for element
introduced option to run individual test with tag
```
[ ] Yes
[ x] No
```
=> add functional test for RET-1014

charts/et-sya/Chart.yaml, charts/et-sya/values.yaml
add redis access key
```
[ ] Yes
[ ] No
```
=> fix master deployment

charts/et-sya/Chart.yaml, charts/et-sya/values.yaml
fixed indentation in chart default values
```
[ ] Yes
[x] No
```
=> trying to fix aat

.github/dependabot.yml, .github/renovate.json
update renovate config to roll all dependencies into weekly pr
tun off dependabot
```
[ ] Yes
[x] No
```
=> Replace dependabot with renovate

src/test/functional/features/empDetailsWhileOnNotice.js, src/test/functional/features/empDetailsWhileWorking.js
JIRA link
[RET-1130](https://tools.hmcts.net/jira/browse/RET-1130)
[RET-1131](https://tools.hmcts.net/jira/browse/RET-1131)
Functional tests for ET frontend employee details section
[ ] Yes
[X] No
=> employmeent details while working and on notice - automation

charts/et-sya/Chart.yaml
=> bump helm chart to v2.4.3

src/test/functional/features/checkyourAnswers.js
JIRA link
[RET-1236](https://tools.hmcts.net/jira/browse/RET-1236)
Functional tests for ET check your answers page
[ ] Yes
[X] No
=> automation for check your answers page

Jenkinsfile_nightly
Running nightly build on ET frontend
[ ] Yes
[X] No
=> added comma separator

src/main/resources/locales/en/translation/template.json, src/main/views/template.njk
https://tools.hmcts.net/jira/browse/RET-1440
```
[ ] Yes
[x] No
```
=> RET-1440 Add smart feedback survey link to banner

src/test/functional/features/etSingleClaimForMyself.js
Functional tests for descimination type has removed as new protoytype pages are in implmentation
[ ] Yes
[X] No
=> commented code for descrimination type

src/test/functional/features/etSingleClaimForMyself.js
Functional tests for descimination type has added back
[ ] Yes
[X] No
=> added  code back for descrimination type

src/test/functional/saucelabs.conf.js, src/test/functional/saucelabsHelper.js
To fix cross browser test failure  due to 
Cannot find module '/opt/jenkins/workspace/i_Nightly_et-sya-frontend_master/src/test/functional/saucelabshelper.js'.
https://build.platform.hmcts.net/view/ET/job/HMCTS_d_to_i_Nightly/job/et-sya-frontend/job/master/3/execution/node/97/log/
```
[ ] Yes
[ X] No
```
=> refactor introduced typo

package.json, src/test/functional/saucelabs.conf.js
Enabled running functional test on nightly
```
[ ] Yes
[ X] No
```
=> enable running functional test on nightly build

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RET-1730
fix mismatch parameter in jenkinsfile
```
[ ] Yes
[X ] No
```
=> fix mismatch Test URL params in jenkinsfile

config/test.json, src/main/controllers/DobController.ts, src/main/definitions/api/caseApiBody.ts, src/main/definitions/case.ts, src/main/definitions/complexTypes/claimantCorrespondence.ts, src/main/definitions/complexTypes/claimantIndividual.ts, src/main/definitions/constants.ts, src/main/helper/ApiFormatter.ts, src/main/modules/oidc/index.ts, src/main/services/CaseService.ts, src/test/routes/date-of-birth.test.ts, src/test/unit/controller/DobController.test.ts, src/test/unit/helper/ApiFormatter.test.ts, src/test/unit/mocks/mockEt1DataModel.ts, src/test/unit/services/CaseService.test.ts
https://tools.hmcts.net/jira/browse/RET-1438
Updated draft case call to API
```
[ ] Yes
[x] No
```
=> RET-1438-Update-draft-case

src/main/assets/scss/main.scss, src/main/assets/scss/utilities/_borders.scss, src/main/resources/locales/en/translation/claim-submitted.json, src/main/views/claim-submitted.njk
https://tools.hmcts.net/jira/browse/RET-1441
add the exit survey to the claim submit page.
```
[ ] Yes
[X ] No
```
=> RET-1441: add the exit survey to the claim submit page.

src/main/resources/locales/en/translation/check-your-answers.json, src/main/resources/locales/en/translation/common.json, src/main/resources/locales/en/translation/new-account-landing.json, src/main/resources/locales/en/translation/still-working.json, src/test/functional/features/checkAndSubmitCliam.js, src/test/functional/features/etStepToMakeYourClaim.js, src/test/unit/views/check-your-answers.test.ts, src/test/unit/views/compensation-outcome.test.ts, src/test/unit/views/date-of-birth.test.ts, src/test/unit/views/desired-claim-outcome.test.ts, src/test/unit/views/new-account-landing.test.ts, src/test/unit/views/past-employer.test.ts, src/test/unit/views/start-date.test.ts, src/test/unit/views/still-working.test.ts, src/test/unit/views/summarise-your-claim.test.ts, src/test/unit/views/telephone-number.test.ts, src/test/unit/views/tribunal-recommendation-outcome.test.ts, src/test/unit/views/update-preference.test.ts
https://tools.hmcts.net/jira/browse/RET-1521
```
[ ] Yes
[ X] No
```
=> 1521: change label to 'save as draft' and update the '/are-you-still-working' page

src/main/resources/locales/en/translation/past-employer.json, src/main/resources/locales/en/translation/still-working.json
https://tools.hmcts.net/jira/browse/RET-1522
```
[ ] Yes
[X ] No
```
=> Ret 1522 update validation messages for past-employer and still-working

Jenkinsfile_nightly, charts/et-sya/Chart.yaml, charts/et-sya/values.aat.template.yaml, charts/et-sya/values.preview.template.yaml, charts/et-sya/values.yaml
https://tools.hmcts.net/jira/browse/RET-865
Attempt to fix failing Fortify Scan stage in nightly build by adding explicit key vault name and setting environment variables from vault secrets.
```
[ ] Yes
[ x] No
```
=> Attempt to fix Fortify Scan stage in nightly build

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RET-1926
Updated Jenkins file to sync with 'perftest' environment using perftest branch.
```
[ ] Yes
[x ] No
```
=> Updated Jenkins file to sync with 'perftest' environment

src/test/functional/features/authPage.js, src/test/functional/features/checkAndSubmitCliam.js, src/test/functional/features/checkyourAnswers.js, src/test/functional/features/empDetailsWhileOnNotice.js, src/test/functional/features/empDetailsWhileWorking.js, src/test/functional/features/employeeGotNewJob.js, src/test/functional/features/employeeNotWorking.js, src/test/functional/features/etSingleClaimForMyself.js, src/test/functional/features/etStepToMakeYourClaim.js, src/test/functional/features/etpage.js, src/test/functional/features/placeOfWork.js, src/test/functional/features/returnToExistingClaim.js
https://tools.hmcts.net/jira/browse/RET-1824
Updated functional tests as per authorization changes
[ ] Yes
[x] No
=> test refactor for authorized pages

charts/et-sya/Chart.yaml
https://tools.hmcts.net/jira/browse/RET-1926
Update Helm chart to specify fully qualified repository name, to try fixing 'perftest' environment AKS cluster deployment.
```
[ ] Yes
[x ] No
```
=> Update Helm chart config setting

charts/et-sya/Chart.yaml
https://tools.hmcts.net/jira/browse/RET-1926
Update Helm chart repository dependency to be fully qualified. Missed this dependency update from previous change.
```
[ ] Yes
[x ] No
```
=> Update Helm chart repository dependency

package.json, yarn.lock
Fix security issue
```
[ ] Yes
[x ] No
```
=> Update Hmcts frontend packages

src/test/api/pact/pact-test/idam/get-user-details.test.ts
…ed the problem of pact test on jenkins by provider.verify and then provider.finalize at line 51
```
[ ] Yes
[ ] No
```
=> Resolve_Pact_Test_Problem

charts/et-sya/Chart.yaml
Helm chart node 2.4.4 -> 2.4.5
```
[ ] Yes
[ ] No
```
=> Update Helm Chart release nodejs to v2.4.5

Jenkinsfile_CNP, src/main/modules/oidc/index.ts, src/test/a11y/a11y.ts
Fix for unstable accessibility tests
```
=> For pa11y testing with post-login pages

src/main/assets/js/index.js, src/main/assets/js/set-styles.ts
https://tools.hmcts.net/jira/browse/RET-2066
Added set-styles.ts to add style values to govuk default frontend classes. In this issue hypens attribute added as auto.
imported set-styles typescript to index.js
```
[X] Yes
[ ] No
```
=> ET-2066 Accessibility issues for et-sya-frontend - Responsive CSS

charts/et-sya/Chart.yaml, package.json, yarn.lock
N/A
Bump Helm +types
```
[ ] Yes
[x] No
```
=> Bump Helm + types

package.json
https://tools.hmcts.net/jira/browse/RET-1906
Refactor fullfunctional test job on Jenkins to run only several tests and not all.
```
[ ] Yes
[x] No
```
=> update fullfuntional tests on jenkins to only run RET-BAT

package.json
Disabled tests on pipeline by removing tag from package.json
```
[ ] Yes
[ x] No
```
=> Removed tag from test:functional to disable tests

package.json
Enable functional tests following environment fix
```
[ ] Yes
[x] No
```
=> enable functional tests

package.json
Temporarily disable functional and cross browser tests 
```
[ ] Yes
[ x] No
```
=> temp disable functional and xbrowser tests

src/main/controllers/CitizenHubController.ts, src/main/controllers/helpers/CaseHelpers.ts, src/main/definitions/constants.ts, src/main/services/CaseService.ts, src/test/unit/helper/ApiFormatter.test.ts, src/test/unit/mocks/mockEt1DataModel.ts, src/test/unit/services/CaseService.test.ts
https://tools.hmcts.net/jira/browse/RET-2538
Enable updating of submitted case's data.
```
[ ] Yes
[x] No
```
=> RET-2538. Add case service method to update a submitted case's data.

config/perftest.json
=> Added perftest config

charts/et-sya/Chart.yaml, charts/et-sya/values.yaml, src/main/pcq/createToken.ts
=> Remove question mark

src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
https://tools.hmcts.net/jira/browse/RET-2556
```
[ ] Yes
[x] No
```
=> RET-2556 - fix invalid acas certificate in func test

src/main/components/form/validator.ts, src/main/controllers/helpers/ErrorHelpers.ts, src/main/resources/locales/en/translation/describe-what-happened.json, src/test/unit/components/validator.test.ts, src/test/unit/controller/DescribeWhatHappenedController.test.ts, src/test/unit/mocks/mockFile.ts
=> RET-2569: Fix file format error not appearing

src/test/end-to-end/features/WIP/checkAndSubmitCliam.js
Remove tag for failing test, refactoring feature to be included within e2e scenario. This feature navigates directly to the check your answers page which causes issues
```
[ ] Yes
[x] No
```
=> remove tag for failing test, feature will be refactored with e2e test

src/main/controllers/LipOrRepController.ts, src/test/routes/lip-or-representative.test.ts, src/test/unit/controller/LipOrRepController.test.ts
https://tools.hmcts.net/jira/browse/RET-2600
```
[ ] Yes
[x] No
```
=> RET-2600 change lip or representative question 

src/main/controllers/helpers/YourDetailsAnswersHelper.ts
https://tools.hmcts.net/jira/browse/RET-2604
Bug fix
```
[ ] Yes
[X] No
```
=> Display No answer for reasonable adjustments

src/main/controllers/WorkAddressController.ts
https://tools.hmcts.net/jira/browse/RET-2609
```
[ ] Yes
[x ] No
```
=> Move handleUpdateDraftCase

sonar-project.properties, src/main/controllers/DobController.ts, src/main/controllers/EndDateController.ts, src/main/controllers/NewJobStartDateController.ts, src/main/controllers/NoticeEndController.ts, src/main/controllers/StartDateController.ts
=> RET-2587: Temporary fix for pre-populated date fields

src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
=> Nightly dev

src/main/controllers/DescribeWhatHappenedController.ts, src/main/controllers/helpers/ErrorHelpers.ts, src/main/controllers/helpers/PageContentHelpers.ts, src/main/resources/locales/en/translation/describe-what-happened.json, src/test/end-to-end/config.js, src/test/unit/controller/DescribeWhatHappenedController.test.ts, src/test/unit/controller/helpers/ErrorHelpers.test.ts
=> RET-2661: Fix for non uploaded file being visible

src/test/end-to-end/config.js
=> Revert test url back to AAT

src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
=> Disable test

src/main/pcq/index.ts
https://tools.hmcts.net/jira/browse/RET-2644
Add logging
```
[ ] Yes
[x] No
```
=> Add pcq logging

src/test/unit/controller/TypeOfClaimController.test.ts
https://tools.hmcts.net/jira/browse/RET-2665.
Add tests to RET-2665.
No breaking changes.
=> RET-2665 tests

src/main/controllers/SubmittedCaseDocumentController.ts, src/main/controllers/helpers/EmploymentAnswersHelper.ts, src/main/definitions/constants.ts, src/main/routes/routes.ts, src/main/services/CaseSelectionService.ts, src/test/unit/controller/SubmittedCaseDocumentController.test.ts, src/test/unit/mocks/mockApp.ts, src/test/unit/mocks/mockApplications.ts, src/test/unit/mocks/mockRequest.ts, src/test/unit/views/check-your-answers.test.ts
https://tools.hmcts.net/jira/browse/RET-2681
Fixing download form not working on claimant applications page.
Also fixes issues with CYA page:
- Hides past employer question when Unfair Dismissal
- Shows notice period question only if it was was asked
- Displays notice period answers when 'Working Notice' is selected
```
[ ] Yes
[x] No
```
=> RET-2663 - PDF View link is broken

src/main/controllers/helpers/EmploymentAnswersHelper.ts, src/test/unit/mocks/mockRequest.ts
https://tools.hmcts.net/jira/browse/RET-2675
https://tools.hmcts.net/jira/browse/RET-2680
Fix CYA page new job and notice end
```
[ ] Yes
[x] No
```
=> RET-2675 - Fix CYA page new job and notice end

src/main/definitions/constants.ts, src/test/end-to-end/config.js
=> Ret 2673 2

src/main/resources/locales/en/translation/tasklist-check.json
https://tools.hmcts.net/jira/browse/RET-2694
Fix template error on section completed by adding an error message for the yes/no control
```
[ ] Yes
[x] No
```
=> RET-2694: Fix template error on section completed

package.json, src/test/smoke/codecept.smoke.conf.js
=> Disable Tests for ITHC

package.json
=> reenable tests

src/test/smoke/codecept.smoke.conf.js
=> Uncomment out test line

package.json, src/test/smoke/codecept.smoke.conf.js, yarn.lock
=> Fix Smoke Tests

src/test/end-to-end/pages/claimDetails/claimDet.js, src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js, src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
Add hard wait after completing each section (personal details, employment and respondent details and claim details)
```
[ ] Yes
[x] No
```
=> Add hard wait after completing each section

src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
=> add retry option to help the pipeline

src/main/controllers/RespondentAddressController.ts, src/main/controllers/helpers/RespondentAnswersHelper.ts, src/test/unit/controller/RespondentAddressController.test.ts
https://tools.hmcts.net/jira/browse/RET-2686
Update journey for claimant not employed by respondent
```
[ ] Yes
[x] No
```
=> RET-2686 - Update journey for claimant not employed by respondent

src/test/end-to-end/config.js
=> change test url to pick up preview url

src/test/end-to-end/features/WIP/empDetailsWhileWorking.js, src/test/end-to-end/pages/employmentDetails/stillWorkingPages.js, src/test/end-to-end/pages/employmentDetails/workingNoticePeriodPages.js
=> fix failing test in R1.1.0.2

src/main/pcq/index.ts
Reverts hmcts/et-sya-frontend#498
=> Revert "PCQ url"

src/test/end-to-end/features/WIP/empDetailsWhileWorking.js, src/test/end-to-end/pages/employmentDetails/stillWorkingPages.js, src/test/end-to-end/pages/employmentDetails/workingNoticePeriodPages.js
N/A
Fix failing functional tests following accessibility changes
```
[ ] Yes
[x] No
```
=> Fix failing functional tests

src/main/controllers/helpers/CaseHelpers.ts, src/test/unit/controller/ReturnToExistingController.test.ts
https://tools.hmcts.net/jira/browse/RET-2258
Additional refactor
```
[ ] Yes
[x] No
```
=> RET-2258 - Reuse post logic

src/main/views/citizen-hub-sidebar.njk
https://tools.hmcts.net/jira/browse/RET-2870
Updated contact link with https://www.gov.uk/guidance/employment-tribunal-offices-and-venues
```
[ ] Yes
[X] No
```
=> Ret 2870 contact link update

Jenkinsfile_CNP, src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js, src/test/routes/new-job.test.ts
https://tools.hmcts.net/jira/browse/RET-2738
Updates for improvement of et-sya-frontend tests.
```
[ ] Yes
[X] No
```
=> Ret-2738 Improve et-sya-frontend tests

src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
=> fix address line failure

src/main/address/index.ts, src/main/controllers/CitizenHubDocumentController.ts, src/main/pcq/index.ts, src/main/views/citizen-hub-sidebar.njk, src/main/views/citizen-hub.njk, src/test/end-to-end/config.js, src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js, src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
=> Deployed to Demo : Release1.1Fixes

src/main/controllers/ChangeDetailsController.ts, src/main/controllers/helpers/RouterHelpers.ts, src/test/unit/controller/ChangeDetailsControllerTest.test.ts
https://tools.hmcts.net/jira/browse/RET-2810
Fix redirect for respondent pages
```
[ ] Yes
[x] No
```
=> RET-2810 - Fix redirect for respondent pages

src/main/controllers/ChangeDetailsController.ts, src/main/controllers/CitizenHubDocumentController.ts, src/main/controllers/helpers/RouterHelpers.ts, src/main/helper/ApiFormatter.ts, src/test/unit/controller/ChangeDetailsControllerTest.test.ts, src/test/unit/helper/ApiFormatter.test.ts, yarn.lock
N/A
Fix merge conflicts
```
[ ] Yes
[x] No
```
=> 1.1.1 mergefix

src/main/controllers/ReturnToExistingController.ts, src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js, src/test/routes/return-to-existing.test.ts
N/A
Reset guid on return to existing
```
[ ] Yes
[x] No
```
=> Reset guid on return to existing

src/main/views/contact-the-tribunal.njk
https://tools.hmcts.net/jira/browse/RET-2261 
Fix link sizes.
```
[ ] Yes
[x] No
```
=> RET-2261. Fix link sizes.

src/main/resources/locales/en/translation/template.json
Remove language toggle in header as hotfix for R1.1.0.2.
```
[ ] Yes
[x ] No
```
=> Remove language toggle

src/main/resources/locales/en/translation/contact-application.json, src/main/views/contact-application.njk
https://tools.hmcts.net/jira/browse/RET-2734
```
[ ] Yes
[X] No
```
=> RET-2734 - small fixes

src/main/resources/locales/en/translation/home.json, src/main/resources/locales/en/translation/valid-no-acas-reason.json, src/test/end-to-end/helpers/commonFlowContent.js
https://tools.hmcts.net/jira/browse/RET-2941
https://tools.hmcts.net/jira/browse/RET-2935
Added opens in new tab text
```
[ ] Yes
[X] No
```
=> RET-2941 and RET-2935

src/main/resources/locales/cy/translation/citizen-hub.json, src/main/resources/locales/cy/translation/claim-details.json, src/main/resources/locales/cy/translation/claim-type-discrimination.json, src/main/resources/locales/cy/translation/claim-type-pay.json, src/main/resources/locales/cy/translation/claimant-applications.json, src/main/resources/locales/cy/translation/common.json, src/main/resources/locales/cy/translation/compensation.json, src/main/resources/locales/cy/translation/date-of-birth.json, src/main/resources/locales/cy/translation/describe-what-happened.json, src/main/resources/locales/cy/translation/et1-details.json, src/main/resources/locales/cy/translation/sex-and-title.json, src/main/resources/locales/cy/translation/sidebar-contact-us.json, src/main/resources/locales/cy/translation/tell-us-what-you-want.json, src/main/resources/locales/cy/translation/template.json, src/main/resources/locales/cy/translation/tribunal-recommendation.json, src/main/resources/locales/cy/translation/type-of-claim.json
https://tools.hmcts.net/jira/browse/RET-2972
Entering Welsh language translations.
```
[ ] Yes
[X] No
```
=> Welsh language journey - enter translations

src/main/resources/locales/cy/translation/common.json
N/A
Replace removed placeholder
```
[ ] Yes
[x] No
```
=> Replace removed placeholder

src/main/controllers/helpers/LanguageHelper.ts
Minor fixes for SonarQube to reduce "code smell".
JIRA link
https://tools.hmcts.net/jira/browse/RET-3005
```
[ ] Yes
[x ] No
```
=> RET-3005: Fix LanguageHelper

src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
Added Date of Birth (optional)
```
[ ] Yes
[ ] No
```
=> Updated enterPersonalDetails.js

Jenkinsfile_CNP, yarn.lock
https://tools.hmcts.net/jira/browse/RET-2038
To not to start functional tests before passing accessibility tests, accessibility tests are moved just before functional tests in Jenkins.
```
[ ] Yes
[X] No
```
=> Ret-2038 Prebuild automation for accessibility

src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js, src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
=> Ret 2936 automation

src/main/controllers/ApplicationCompleteController.ts, src/main/definitions/constants.ts, src/main/modules/routes/routes.ts, src/main/resources/locales/cy/translation/application-complete.json, src/main/resources/locales/en/translation/application-complete.json, src/main/views/application-complete.njk, src/test/routes/application-complete.test.ts, src/test/unit/controller/ApplicationCompleteController.test.ts, src/test/unit/views/application-complete.test.ts
https://tools.hmcts.net/jira/browse/RET-2619
Initial commit adding template for TSE application complete page
```
[ ] Yes
[x] No
```
=> Ret 2619 - Applications complete page- Placeholder

package.json, yarn.lock
N/A
Fix package security issues 
```
[ ] Yes
[x] No
```
=> Fix package security

package.json, src/main/assets/js/address/submit.ts, src/main/modules/oidc/index.ts, src/main/resources/locales/cy/translation/citizen-hub.json, src/main/resources/locales/cy/translation/claim-type-discrimination.json, src/main/resources/locales/cy/translation/template.json, src/main/resources/locales/en/translation/citizen-hub.json, src/main/resources/locales/en/translation/template.json, src/main/views/citizen-hub-notification-banner.njk, src/main/views/citizen-hub.njk, src/main/views/claim-details.njk, src/main/views/document-view.njk, src/main/views/response-from-respondent-view.njk, src/main/views/template.njk, src/test/end-to-end/pages/claimDetails/claimDet.js, yarn.lock
https://tools.hmcts.net/jira/browse/RET-3035
Fixes and enhancements 
```
[ ] Yes
[x] No
```
=> Ret 3035 - Bug fixes

src/main/controllers/helpers/CaseHelpers.ts, src/main/controllers/helpers/FormHelpers.ts
https://tools.hmcts.net/jira/browse/RET-3001
Added trimFormData for string input types to trim both left and right spaces of any string input value.
```
[X] Yes
[ ] No
```
=> Ret-3001 Trimming spaces from start and end of string inputs

charts/et-sya/Chart.yaml
=> Helm Chart

src/test/unit/views/check-your-answers.test.ts
Update locators
```
[ ] Yes
[X] No
```
=> Update locators in test

src/main/resources/locales/en/translation/accessibility-statement.json
https://tools.hmcts.net/jira/browse/RET-3036
Updated published date as 19 January 2023
```
[ ] Yes
[X] No
```
=> Ret-3036 Adding Accessibility Statement to Footer Menu

src/main/controllers/CitizenHubController.ts, src/main/controllers/CitizenHubDocumentController.ts, src/main/controllers/helpers/CaseHelpers.ts, src/test/end-to-end/features/WIP/empDetailsWhileWorking.js, src/test/end-to-end/features/functionalTests/haveYouCompletedThisSectionValidation.js, src/test/unit/mocks/mockEt1DataModel.ts
N/A
Resolve after merge
```
[ ] Yes
[x] No
```
=> Update default contact tribunal status

charts/et-sya/Chart.yaml
N/A
Bump node chart to 2.4.13
```
[ ] Yes
[x] No
```
=> Bump node chart to 2.4.13

src/main/resources/locales/en/translation/application-complete.json
Translation file application-complete.json fixes
```
[ ] Yes
[x ] No
```
=> RET-2619-fix

Jenkinsfile_nightly
=> Jenkinsfile_nightly fix

src/main/controllers/ApplicationCompleteController.ts, src/main/controllers/ContactTheTribunalSelectedController.ts, src/main/controllers/CopyToOtherPartyController.ts, src/main/controllers/helpers/ErrorHelpers.ts, src/main/definitions/case.ts, src/main/resources/locales/cy/translation/contact-the-tribunal-cya.json, src/main/resources/locales/cy/translation/copy-to-other-party.json, src/main/resources/locales/en/translation/contact-the-tribunal-cya.json, src/main/resources/locales/en/translation/copy-to-other-party.json, src/main/services/CaseService.ts, src/main/views/contact-the-tribunal-cya.njk, src/main/views/copy-to-other-party.njk
https://tools.hmcts.net/jira/browse/RET-2617
Claimant can advise whether they want to copy correspondence to the LR/Respondent or not (when both parties are system users), to satisfy the rules of procedure (as per Rule 92) . 
```
[ ] Yes
[X] No
```
=> Ret 2617 - Rule 92 question - both parties are system users (CitizenUI)

src/main/controllers/helpers/RespondentAnswersHelper.ts
https://tools.hmcts.net/jira/browse/RET-3107
```
[ ] Yes
[x] No
```
=> RET-3107. Fix acas 'no' translation

charts/et-sya/Chart.yaml
https://tools.hmcts.net/jira/browse/RET-3133
Upgrade to helm-nodejs version 2.4.13
```
[X] Yes
[ ] No
```
=> Ret-3133 Upgrade to helm-nodejs version 2.4.13

src/main/controllers/ContactTheTribunalSelectedController.ts, src/main/definitions/constants.ts, src/main/resources/locales/en/translation/contact-the-tribunal-selected.json, src/main/views/contact-the-tribunal-selected.njk
https://tools.hmcts.net/jira/browse/RET-2616
Bug fixes: 
Contact the tribunal selected page fixes: 
- Change the fontsize in njk
- typo in translations
- cancel link redirect to citizen hub                   
```
[ ] Yes
[x ] No
```
=> RET-2616-fix

src/main/resources/locales/cy/translation/work-postcode.json
https://tools.hmcts.net/jira/browse/RET-3022
Adding translations
```
[ ] Yes
[x] No
```
=> Add work postcode translations

src/main/controllers/ContactTheTribunalCYAController.ts, src/main/controllers/helpers/ContactTheTribunalCYAHelper.ts, src/main/controllers/helpers/DocumentHelpers.ts, src/main/definitions/case.ts, src/main/helper/ApiFormatter.ts, src/main/views/contact-the-tribunal-cya.njk, src/test/unit/helper/ApiFormatter.test.ts
###Jira Link
https://tools.hmcts.net/jira/browse/RET-2618
Allow the Claimant to check the answers they have provided when Contacting the tribunal about something and make any changes (if required) before submission to complete the request.
NB Upon submission the system should activate the 'Your requests and applications' link on the case overview/hub page, and update the link status to ‘In progress’
User Story
As a Claimant, I want to be able to review the answers/comments I have entered to contact the tribunal about something, So that I can make any changes (if required) before submitting my request
```
[ ] Yes
[x ] No
```
=> RET-2618-v2

src/main/controllers/CopyToOtherPartyController.ts
Related to https://tools.hmcts.net/jira/browse/RET-2617
Cleared session errors to remove persisting error messages.
```
[ ] Yes
[X] No
```
=> Ret 2617 - fix - clear session errors

src/main/controllers/ContactTheTribunalCYAController.ts, src/main/controllers/SubmitTribunalCYAController.ts, src/main/controllers/helpers/ContactTheTribunalCYAHelper.ts, src/main/modules/routes/routes.ts, src/main/resources/locales/cy/translation/contact-the-tribunal-cya.json, src/main/resources/locales/en/translation/contact-the-tribunal-cya.json, src/test/unit/controller/SubmitTseController.test.ts
https://tools.hmcts.net/jira/browse/RET-2618
Small fixes for RET-2618:
Added CYA field for the reason not to copy the application to other party.
Improved Submit controller name and CYA helper method name.
=> Ret 2618 small improvements

src/main/controllers/ApplicationDetailsController.ts, src/main/controllers/helpers/DocumentHelpers.ts, src/test/unit/controller/helpers/DocumentHelpers.test.ts
https://tools.hmcts.net/jira/browse/RET-2288
Fixed file size formatting, to view download link with proper filesize dimensions.
```
[ ] Yes
[x ] No
```
=> RET-2288-fix: Fixed file size formatting

src/main/modules/properties-volume/index.ts, src/test/unit/translations.spec.ts
Reducing test logging from over ~5700 to ~650
=> Fix logging

src/main/controllers/ContactTheTribunalSelectedController.ts, src/main/controllers/CopyToOtherPartyController.ts, src/main/controllers/helpers/ErrorHelpers.ts, src/main/resources/locales/cy/translation/copy-to-other-party.json, src/main/resources/locales/en/translation/copy-to-other-party.json, src/test/unit/controller/helpers/ErrorHelpers.test.ts, yarn.lock
Fix validation on https://tools.hmcts.net/jira/browse/RET-2617
```
[ ] Yes
[X] No
|```
=> Fix validation on 2617

yarn.lock
N/A
yarn v3 update
```
[ ] Yes
[x] No
```
=> Add missing packages

src/test/unit/controller/SubmitTseController.test.ts
Additional test changes for SubmitTse application
```
[ ] Yes
[ x] No
```
=> RET-2289-test: Add additional checks to SubmitTseController test

charts/et-sya/Chart.yaml
=> Bump chart

src/main/modules/routes/routes.ts, src/main/views/application-complete.njk
https://tools.hmcts.net/jira/browse/RET-3201
```
[ ] Yes
[x] No
```
=> Remove backlink from application-complete page

src/main/components/form/validator.ts, src/main/controllers/TypeOfClaimController.ts, src/main/controllers/helpers/ErrorHelpers.ts, src/main/resources/locales/cy/translation/type-of-claim.json, src/main/resources/locales/en/translation/type-of-claim.json, src/test/unit/components/validator.test.ts
https://tools.hmcts.net/jira/browse/RET-3102
```
[ ] Yes
[X] No
```
=> Ret 3102 1500 chars limit

src/main/controllers/helpers/ErrorHelpers.ts, src/main/resources/locales/cy/translation/contact-the-tribunal-selected.json, src/main/resources/locales/en/translation/contact-the-tribunal-selected.json, src/test/unit/controller/ContactTheTribunalSelectedController.test.ts
https://tools.hmcts.net/jira/browse/RET-2973
```
[ ] Yes
[X] No
```
=> RET-2973. Restrict free text for TSE

src/main/components/form/form.ts, src/main/controllers/helpers/ErrorHelpers.ts, src/test/unit/components/form.test.ts, src/test/unit/controller/ContactTheTribunalSelectedController.test.ts, src/test/unit/controller/helpers/ErrorHelpers.test.ts
https://tools.hmcts.net/jira/browse/RET-3245
```
[ ] Yes
[X] No
```
=> 3245 - Improve test coverage

src/main/components/form/validator.ts, src/main/controllers/TypeOfClaimController.ts, src/main/controllers/helpers/ErrorHelpers.ts, src/main/resources/locales/cy/translation/type-of-claim.json, src/main/resources/locales/en/translation/type-of-claim.json, src/test/unit/components/validator.test.ts
https://tools.hmcts.net/jira/browse/RET-3102
```
[ ] Yes
[X] No
```
=> Ret 3102 100 chars limit

src/main/controllers/helpers/PageContentHelpers.ts, src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts, src/test/unit/controller/helpers/PageContentHelpers.test.ts
https://tools.hmcts.net/jira/browse/RET-3244
Uses new field applicationState rather status
```
[X] Yes
[ ] No
```
=> RET-3244 - Add application state

Jenkinsfile_CNP
=> enable slack notifications

charts/et-sya/Chart.yaml, src/main/modules/oidc/index.ts
N/A
Fix fortify scan issue 
```
[ ] Yes
[x] No
```
=> Set language param

src/main/controllers/CaseDocumentController.ts, src/main/controllers/CheckYourAnswersController.ts, src/main/controllers/ClaimSubmittedController.ts, src/main/controllers/TypeOfClaimController.ts, src/main/definitions/appRequest.ts, src/main/helper/ApiFormatter.ts, src/main/views/claim-submitted.njk, src/test/unit/controller/CaseDocumentController.test.ts, src/test/unit/controller/CheckAnswers.test.ts, src/test/unit/mocks/mockApp.ts, src/test/unit/mocks/mockRequest.ts
https://tools.hmcts.net/jira/browse/RET-2917
-----
Update to remove claim data from session after case submission.
-----
```
[X] Yes
[ ] No
```
=> Ret-2917 Remove session data after submission of claim

src/main/controllers/helpers/ErrorHelpers.ts, src/test/unit/controller/helpers/ErrorHelpers.test.ts
N/A
Fix merge issues
```
[ ] Yes
[x] No
```
=> Fix merge issues

src/main/controllers/CitizenHubController.ts, src/main/controllers/RespondToApplicationController.ts, src/main/controllers/helpers/PageContentHelpers.ts, src/test/unit/controller/ApplicationDetailsController.test.ts, src/test/unit/controller/RespondToApplicationController.test.ts, src/test/unit/controller/helpers/PageContentHelpers.test.ts, src/test/unit/mocks/mockRequest.ts
N/A
Test coverage
```
[ ] Yes
[x] No
```
=> Ret 2785 more tests

src/main/controllers/SupportingMaterialController.ts, src/main/resources/locales/cy/translation/respondent-supporting-material.json, src/main/resources/locales/en/translation/respondent-supporting-material.json
Fix supporting material download condition(RET-2787 ticket) and RET-2788 translation jsons
```
[ ] Yes
[x ] No
```
=> RET-2788 fix

charts/et-sya/Chart.yaml, src/main/controllers/RespondentApplicationDetailsController.ts, src/main/controllers/helpers/PageContentHelpers.ts, src/main/definitions/definition.ts, src/main/views/citizen-hub-notification-banner.njk, src/main/views/respondent-application-details.njk, src/test/unit/controller/RespondentApplicationDetailsController.test.ts, src/test/unit/controller/helpers/PageContentHelpers.test.ts, src/test/unit/views/respondent-applications.test.ts
https://tools.hmcts.net/jira/browse/RET-2786
```
[ ] Yes
[X] No
```
=> Ret 2786 final

src/main/controllers/helpers/ApplicationDetailsHelper.ts, src/main/services/CaseService.ts, src/test/unit/controller/RespondentApplicationDetailsController.test.ts, src/test/unit/controller/helpers/ApplicationDetailsHelper.test.ts, src/test/unit/views/respondent-application-details.test.ts
N/A
Add dymnamic application type description
```
[ ] Yes
[x] No
```
=> Add dymnamic application type description

src/test/end-to-end/features/WIP/empDetailsWhileOnNotice.js, src/test/end-to-end/features/WIP/empDetailsWhileWorking.js, src/test/end-to-end/features/WIP/employeeGotNewJob.js, src/test/end-to-end/features/WIP/employeeNotWorking.js, src/test/end-to-end/features/WIP/etMultipleClaimsForMyself.js, src/test/end-to-end/features/WIP/returnToExistingClaim.js
=> Remove wip from running in pipeline

src/main/controllers/CaseDocumentController.ts, src/main/controllers/helpers/DocumentHelpers.ts, src/test/unit/controller/CaseDocumentController.test.ts, src/test/unit/services/CaseService.test.ts
https://tools.hmcts.net/jira/browse/RET-3381
-----
Update for checking documents to download, not by session but user.
-----
```
[ ] Yes
[X] No
```
=> RET-3381 Document download update

src/main/assets/js/index.js, src/main/assets/js/submit-claim.ts, src/main/views/check-your-answers.njk, src/test/end-to-end/pages/checkYourAnswers/checkYourAnswers.js
https://tools.hmcts.net/jira/browse/RET-3435
-----
Implementation for disabling submit case button while case is being submitted. This update is implemented for check-your-answers page.
-----
```
[ ] Yes
[X] No
```
=> RET-3435 Disabling submit button to not trigger submit case event twice

src/main/controllers/CaseDocumentController.ts, src/main/controllers/helpers/DocumentHelpers.ts, src/test/unit/controller/CaseDocumentController.test.ts, src/test/unit/controller/helpers/DocumentHelpers.test.ts
https://tools.hmcts.net/jira/browse/RET-3381
-----
Updates for document viewer to accept different types of documents.
```
[ ] Yes
[X] No
```
=> RET-3381 Citizen hub document problem

src/main/controllers/AttachmentController.ts
https://tools.hmcts.net/jira/browse/RET-2929
Fix the condition in AttachmentController for contactTheApplicationFile and supportingMaterialFile.
```
[ ] Yes
[x ] No
```
=> RET-2929_bug_fix

src/main/definitions/contact-applications.ts
Add 'withdraw' as a type b application.
```
[ ] Yes
[x] No
```
=> Add withdraw as a type b application

src/main/definitions/constants.ts, src/main/services/CaseService.ts, src/test/unit/controller/YourAppsToTheTribunalController.test.ts, src/test/unit/services/CaseService.test.ts
N/A
Adding test coverage
```
[ ] Yes
[x] No
```
=> Test coverage

src/main/controllers/BundlesCompletedController.ts, src/main/definitions/constants.ts, src/main/modules/routes/routes.ts, src/main/resources/locales/cy/translation/bundles-completed.json, src/main/resources/locales/en/translation/bundles-completed.json, src/main/views/bundles-completed.njk, src/test/routes/bundles-completed.test.ts, src/test/unit/controller/BundlesCompletedController.test.ts, src/test/unit/views/bundles-completed.test.ts
https://tools.hmcts.net/jira/browse/RET-3093
Add Bundles Completed page
```
[ ] Yes
[x] No
```
=> Ret 3093 - Add Bundles Completed page

src/main/controllers/CitizenHubController.ts, src/main/controllers/TribunalOrderOrRequestDetailsController.ts, src/main/controllers/helpers/DocumentHelpers.ts, src/main/controllers/helpers/PageContentHelpers.ts, src/main/controllers/helpers/RespondentHelpers.ts, src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts, src/main/controllers/helpers/TseRespondentApplicationHelpers.ts
N/A
Fix optional chain expression code smell
```
[ ] Yes
[x] No
```
=> Code smells

sonar-project.properties, src/main/components/form/validator.ts, src/test/unit/components/validator.test.ts
=> RET-3585 (#797)

src/main/controllers/CitizenHubDocumentController.ts, src/main/controllers/helpers/DocumentHelpers.ts
=> Fix et3 form link

src/main/components/form/validator.ts, src/main/controllers/helpers/ErrorHelpers.ts, src/main/resources/locales/cy/translation/acas-cert-num.json, src/main/resources/locales/en/translation/acas-cert-num.json, src/test/unit/controller/helpers/ErrorHelpers.test.ts, src/test/unit/mocks/mockUserCaseComplete.ts
https://tools.hmcts.net/jira/browse/RET-2924
```
[ ] Yes
[X] No
```
=> duplicate acas number validation

src/main/controllers/CitizenHubController.ts, src/main/controllers/RespondentApplicationDetailsController.ts, src/main/controllers/RespondentApplicationsController.ts, src/main/controllers/helpers/CitizenHubHelper.ts, src/main/controllers/helpers/TseRespondentApplicationHelpers.ts, src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts, src/main/definitions/constants.ts, src/main/resources/locales/cy/translation/respondent-applications.json, src/main/resources/locales/en/translation/respondent-applications.json, src/main/services/CaseService.ts, src/test/unit/controller/RespondentApplicationDetailsController.test.ts, src/test/unit/controller/helpers/CaseHelpers.test.ts, src/test/unit/controller/helpers/CitizenHubHelper.test.ts, src/test/unit/controller/helpers/TseRespondentApplicationHelpers.test.ts, src/test/unit/mocks/mockApplications.ts, src/test/unit/mocks/mockUserCase.ts, src/test/unit/services/CaseService.test.ts, src/test/unit/test-helpers/clone.ts
https://tools.hmcts.net/jira/browse/RET-3697
```
[ ] Yes
[x] No
```
=> RET-3697. Respondents applications page statuses

src/main/controllers/TribunalOrderOrRequestDetailsController.ts, src/main/views/tribunal-order-or-request-details.njk, src/test/unit/controller/TribunalOrderOrRequestDetailsController.test.ts
https://tools.hmcts.net/jira/browse/RET-3715
```
[ ] Yes
[x] No
```
=> RET-3715 remove ability to respond when response not required

src/main/controllers/CheckYourAnswersController.ts, src/main/controllers/TypeOfClaimController.ts, src/main/controllers/helpers/FormHelpers.ts, src/main/resources/locales/cy/translation/check-your-answers.json, src/main/resources/locales/en/translation/check-your-answers.json
Reverts hmcts/et-sya-frontend#818
=> Revert "RET-3452"

src/main/controllers/CitizenHubController.ts, src/main/controllers/RespondentApplicationDetailsController.ts, src/main/controllers/helpers/CitizenHubHelper.ts, src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts, src/main/definitions/constants.ts, src/main/definitions/hub.ts, src/main/resources/locales/cy/translation/citizen-hub.json, src/main/resources/locales/en/translation/citizen-hub.json, src/main/services/CaseService.ts, src/main/views/respondent-applications.njk, src/test/unit/controller/RespondentApplicationDetailsController.test.ts, src/test/unit/controller/helpers/CitizenHubHelper.test.ts, src/test/unit/controller/helpers/TseRespondentApplicationHelpers.test.ts, src/test/unit/mocks/mockApplications.ts, src/test/unit/services/CaseService.test.ts
https://tools.hmcts.net/jira/browse/RET-3684
Status update for respondents applications
```
[ ] Yes
[X] No
```
=> RET-3684. Status update for respondents applications.

package.json, src/main/controllers/ApplicationDetailsController.ts, src/main/controllers/RespondToTribunalResponseController.ts, src/main/controllers/RespondentApplicationDetailsController.ts, src/main/definitions/constants.ts, src/main/modules/routes/routes.ts, src/main/resources/locales/cy/translation/respond-to-tribunal-response.json, src/main/resources/locales/en/translation/respond-to-tribunal-response.json, src/main/views/application-details.njk, src/main/views/respond-to-tribunal-response.njk, src/main/views/respondent-application-details.njk, src/test/unit/controller/RespondToTribunalResponseController.test.ts, src/test/unit/views/respond-to-tribunal-response.test.ts, yarn.lock
https://tools.hmcts.net/jira/browse/RET-3791
This screen allows claimant to Respond to request from the tribunal within an application after receiving a notification of a request from the tribunal. They can choose to enter free text response &/or upload supporting material (if required)
```
[ ] Yes
[x] No
```
=> Ret 3791 - Response to tribunal page 

package.json, yarn.lock
N/A
"resolutions": "jsdom": "^22.1.0"
```
[ ] Yes
[ ] No
```
=> resolutions - jsdom

src/main/controllers/ClaimDetailsController.ts, src/main/controllers/helpers/DocumentHelpers.ts, src/main/definitions/constants.ts, src/main/helper/ApiFormatter.ts, src/main/resources/locales/cy/translation/et1-details.json, src/main/resources/locales/en/translation/et1-details.json, src/main/views/claim-details.njk, src/test/unit/controller/helpers/DocumentHelpers.test.ts
Reverts hmcts/et-sya-frontend#857
=> Revert "RET-2919"

src/main/controllers/TribunalResponseCYAController.ts
https://tools.hmcts.net/jira/browse/RET-3792
Fix broken page
```
[ ] Yes
[X] No
```
=> RET-3792 - Fix Tribunal CYA page

src/main/controllers/ApplicationDetailsController.ts, src/main/controllers/CitizenHubController.ts, src/main/controllers/JudgmentDetailsController.ts, src/main/controllers/RespondToTribunalResponseController.ts, src/main/controllers/RespondentApplicationDetailsController.ts, src/main/controllers/helpers/AdminNotificationHelper.ts, src/main/controllers/helpers/AllDocumentsHelper.ts, src/main/controllers/helpers/DocumentHelpers.ts, src/main/controllers/helpers/JudgmentHelpers.ts, src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts, src/main/views/application-details.njk, src/main/views/respondent-application-details.njk, src/test/unit/controller/helpers/DocumentHelpers.test.ts, src/test/unit/controller/helpers/JudgmentHelpers.test.ts, src/test/unit/mocks/mockUserCaseWithDecisionsAndJudgments.ts
https://tools.hmcts.net/jira/browse/RET-3690
Bug fixes after updating application states
```
[ ] Yes
[x] No
```
=> Ret 3690 fixes

src/main/controllers/RespondentApplicationCYAController.ts, src/main/controllers/TribunalResponseCYAController.ts, src/main/controllers/helpers/CaseHelpers.ts, src/main/definitions/case.ts, src/main/services/CaseService.ts, src/test/unit/controller/RespondentApplicationCYAController.test.ts, src/test/unit/controller/TribunalResponseCYAController.test.ts
https://tools.hmcts.net/jira/browse/RET-3796
https://tools.hmcts.net/jira/browse/RET-3797
```
[ ] Yes
[ ] No
```
=> RET 3796, 3797 Application response: add value to show if responding to a tribunal order/request or not 

src/main/controllers/citizen-hub/CitizenHubController.ts, src/main/controllers/citizen-hub/CitizenHubDocumentController.ts, src/main/modules/routes/routes.ts, src/test/unit/controller/citizen-hub/CitizenHubController.test.ts, src/test/unit/controller/citizen-hub/CitizenHubDocumentController.test.ts
Tech debt to group controllers into logically related packages
```
[ ] Yes
[X] No
```
=> RET-0000. Group controllers

src/main/controllers/TypeOfClaimController.ts
=> revert change

src/main/controllers/TypeOfClaimController.ts, src/test/unit/controller/TypeOfClaimController.test.ts
=> Pet 1.1.2.3

src/main/controllers/ApplicationDetailsController.ts, src/main/controllers/RespondentApplicationDetailsController.ts, src/main/controllers/helpers/ApplicationStateHelper.ts, src/main/controllers/helpers/TseRespondentApplicationHelpers.ts, src/main/resources/locales/cy/translation/application-details.json, src/main/resources/locales/en/translation/application-details.json, src/main/views/application-details.njk, src/test/unit/controller/helpers/ApplicationStateHelper.test.ts, src/test/unit/mocks/mockGenericTseCollection.ts
https://tools.hmcts.net/jira/browse/RET-3690
Update handling of responses and requests
```
[ ] Yes
[x] No
```
=> Ret 3690 - Update application states

src/main/controllers/JudgmentDetailsController.ts, src/main/controllers/helpers/CaseHelpers.ts, src/main/services/CaseService.ts, src/test/routes/judgment-details.test.ts
RET-3690
Fix decision state update
```
[X] Yes
[ ] No
```
=> Fix decision state update

charts/et-sya/Chart.yaml, charts/et-sya/values.yaml, config/custom-environment-variables.json, config/default.json, src/main/controllers/ReturnToExistingController.ts, src/main/controllers/TypeOfClaimController.ts, src/main/definitions/constants.ts, src/main/utils/getLegacyUrlFromLng.ts, src/test/routes/return-to-existing.test.ts, src/test/unit/controller/TypeOfClaimController.test.ts, src/test/unit/utils/getLegacyUrlFromLng.test.ts
https://tools.hmcts.net/jira/browse/RET-3785
```
[ ] Yes
[ X] No
```
=> Ret 3785 new

src/main/views/your-applications.njk
https://tools.hmcts.net/jira/browse/RET-3690
Prevent tag transforming to uppercase
```
[ ] Yes
[x] No
```
=> RET-3690 - Prevent tag transforming to uppercase

src/main/controllers/citizen-hub/CitizenHubController.ts, src/main/controllers/helpers/CitizenHubHelper.ts, src/main/definitions/hub.ts, src/test/unit/controller/helpers/CitizenHubHelper.test.ts
=> RET-3901: Fix for Holding page not displayed

src/main/controllers/citizen-hub/CitizenHubController.ts, src/main/controllers/helpers/CitizenHubHelper.ts, src/test/unit/controller/helpers/CitizenHubHelper.test.ts, src/test/unit/views/citizen-hub.test.ts
https://tools.hmcts.net/jira/browse/RET-3684 
Fix showing banner when respondent replies to application
```
[ ] Yes
[x] No
```
=> Ret 3684 banner fix

charts/et-sya/Chart.yaml, src/main/controllers/CaseDocumentController.ts, src/main/controllers/citizen-hub/CitizenHubController.ts, src/main/controllers/citizen-hub/CitizenHubDocumentController.ts, src/main/controllers/helpers/CaseDocumentHelper.ts, src/main/controllers/helpers/CitizenHubHelper.ts, src/main/definitions/constants.ts, src/main/definitions/hub.ts, src/main/resources/locales/cy/translation/citizen-hub.json, src/main/resources/locales/en/translation/citizen-hub.json, src/test/unit/controller/helpers/CaseDocumentHelper.test.ts, src/test/unit/controller/helpers/CitizenHubHelper.test.ts
=> RET-3714: Response from respondent status changes

package.json, yarn.lock
N/A
CVE-2023-26136
```
[ ] Yes
[ ] No
```
=> CVE-2023-26136

package.json, src/main/modules/oidc/index.ts, yarn.lock
https://tools.hmcts.net/jira/browse/RET-3912
Handle redirectUrl properly
```
[ ] Yes
[x ] No
```
=> RET-3912 - Open redirect on logout

src/main/controllers/ApplicationDetailsController.ts, src/main/controllers/RespondToTribunalResponseController.ts, src/main/controllers/RespondentApplicationDetailsController.ts, src/main/controllers/helpers/AdminNotificationHelper.ts, src/main/controllers/helpers/ApplicationDetailsHelper.ts, src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts, src/main/definitions/constants.ts, src/main/services/CaseService.ts, src/main/views/all-judgments.njk, src/test/unit/controller/helpers/AdminNotificationsHelper.test.ts, src/test/unit/mocks/mockGenericTseCollection.ts, src/test/unit/services/CaseService.test.ts
https://tools.hmcts.net/jira/browse/RET-3792
Hides response notifications from the tribunal after viewing
```
[ ] Yes
[x] No
```
=> Ret 3792 fix

src/main/controllers/citizen-hub/CitizenHubController.ts
https://tools.hmcts.net/jira/browse/RET-4052
```
[ ] Yes
[ ] No
```
=> Disable all docs

Jenkinsfile_nightly
=> separate nightly and master username credential

config/development.json, infrastructure/state.tf, package.json, src/main/modules/helmet/index.ts, yarn.lock
https://tools.hmcts.net/jira/browse/RET-4060
-----
Updates to change IDAM port to 5062 and CFTLIB version from 0.19.670 to 0.19.771
-----
```
[ ] Yes
[X] No
```
=> RET-4060 Update IDAM port to 5062

src/main/controllers/TribunalOrdersAndRequestsController.ts, src/main/controllers/citizen-hub/CitizenHubController.ts, src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts, src/main/definitions/complexTypes/sendNotificationTypeItem.ts, src/main/definitions/constants.ts, src/test/unit/controller/helpers/GeneralCorrespondenceHelper.test.ts, src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts, src/test/unit/mocks/mockNotificationItem.ts
https://tools.hmcts.net/jira/browse/RET-4054
Display notification banner for Other (General Correspondence)
```
[ ] Yes
[x] No
```
=> RET-4054 - Display notification banner for Other (General Correspondence)

.github/renovate.json, package.json, src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
https://tools.hmcts.net/jira/browse/RET-4219
Harmonise with HMCTS renovate config. Set up automerge-all but can change it if it introduces issues.
```
[ ] Yes
[x] No
```
=> RET-4219 - Renovate Config Change

charts/et-sya/Chart.yaml, charts/et-sya/values.aat.template.yaml, charts/et-sya/values.preview.template.yaml, charts/et-sya/values.yaml, config/default.json, config/development.json, package.json, src/main/modules/featureFlag/launchDarkly.ts, src/main/modules/properties-volume/index.ts, src/main/views/template-language-disabled.njk, yarn.lock
https://tools.hmcts.net/jira/browse/RET-4232
```
[ ] Yes
[x] No
```
=> RET-4232 - Set up feature flagging

src/main/controllers/citizen-hub/CitizenHubController.ts, src/main/controllers/helpers/CitizenHubHelper.ts, src/main/definitions/storeNotification.ts, src/main/views/citizen-hub-notification-banner.njk, src/test/unit/controller/helpers/CitizenHubHelper.test.ts
CUI side of the Rule 92 for non system user
Update Citizen Hub Notification for future use
```
[ ] Yes
[x] No
```
=> RET-4062 - Citizen Hub Banner

src/main/controllers/StoreTseController.ts, src/main/controllers/StoredApplicationConfirmationController.ts, src/main/definitions/constants.ts, src/test/unit/controller/StoreTseController.test.ts, src/test/unit/controller/StoredApplicationConfirmationController.test.ts, src/test/unit/controller/StoredToSubmitController.test.ts, src/test/unit/views/stored-application-confirmation.test.ts
CUI side of the Rule 92 for non system user
Refactor Store Application for future use
```
[ ] Yes
[ ] No
```
=> RET-4062 - Store Application

src/main/controllers/StoreRespondentController.ts, src/main/controllers/StoredResponseAppConfirmationController.ts, src/main/controllers/TribunalResponseCYANotSystemUserController.ts, src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts, src/main/definitions/constants.ts, src/main/modules/routes/routes.ts, src/main/services/CaseService.ts, src/test/unit/controller/StoreRespondentController.test.ts, src/test/unit/controller/StoredResponseAppConfirmationController.test.ts
CUI side of the Rule 92 for non system user
Store Response of Application
```
[ ] Yes
[x] No
```
=> RET-4062 - Store Response of Application

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf, src/test/routes/notice-end.test.ts
=> Migrate redis cache to Basic sku in non-prod env

infrastructure/state.tf
=> update azurerm version

charts/et-sya/Chart.yaml, charts/et-sya/values.aat.template.yaml, charts/et-sya/values.preview.template.yaml
Bump memory limits to match all other envs
```
[ ] Yes
[X] No
```
=> Memory bump

Dockerfile, package.json
=> RET-4324 - Switch to tsc & yarn node over ts-node

src/main/modules/helmet/index.ts
https://tools.hmcts.net/jira/browse/RET-4337
starred tagmanager.google.com
```
[ ] Yes
[ x] No
```
=> RET-4337 - Google Analytics CSP change

README.md
N/A
Couple of lines
```
[] Yes
[x ] No
```
=> Update NodeJS version in readme

src/main/controllers/StoredResponseTribunalConfirmationController.ts, src/main/controllers/StoredToSubmitController.ts, src/main/controllers/StoredToSubmitResponseController.ts, src/main/controllers/TribunalResponseCYANotSystemUserController.ts, src/main/controllers/TribunalResponseStoreController.ts, src/main/controllers/helpers/CitizenHubHelper.ts, src/main/controllers/helpers/StoredToSubmitHelpers.ts, src/main/definitions/constants.ts, src/main/modules/routes/routes.ts, src/main/services/CaseService.ts, src/test/unit/controller/StoredResponseTribunalConfirmationController.test.ts, src/test/unit/controller/TribunalResponseStoreController.test.ts, src/test/unit/controller/helpers/CitizenHubHelper.test.ts
Store Response to Tribunal
```
[ ] Yes
[ ] No
```
=> RET-4062 - Store Response to Tribunal

src/main/controllers/StoredResponseTribunalConfirmationController.ts, src/main/controllers/StoredToSubmitTribunalController.ts, src/main/controllers/citizen-hub/CitizenHubController.ts, src/main/controllers/helpers/ApplicationDetailsHelper.ts, src/main/controllers/helpers/CitizenHubHelper.ts, src/main/controllers/helpers/LinkHelpers.ts, src/main/controllers/helpers/StoredToSubmitHelpers.ts, src/main/definitions/case.ts, src/main/definitions/complexTypes/sendNotificationTypeItem.ts, src/main/definitions/constants.ts, src/main/modules/routes/routes.ts, src/main/services/CaseService.ts, src/test/unit/controller/StoredToSubmitTribunalController.test.ts, src/test/unit/controller/helpers/CitizenHubHelper.test.ts, src/test/unit/controller/helpers/LinkHelpers.test.ts, src/test/unit/controller/helpers/StoredToSubmitHelpers.test.ts
Submit Stored Response to Tribunal
```
[ ] Yes
[ ] No
```
=> RET-4062 - Submit Stored Response to Tribunal

src/main/controllers/RespondentSupportingMaterialController.ts, src/test/unit/controller/RespondentSupportingMaterialController.test.ts
Update RespondentSupportingMaterialController
```
[ ] Yes
[ ] No
```
=> RET-4062 - Respondent Supporting Material

src/main/definitions/constants.ts
Update API Links
```
[ ] Yes
[ ] No
```
=> RET-4062 - Update api links

src/main/definitions/constants.ts
=> Update bundles endpoint

src/main/controllers/TribunalRespondToOrderController.ts
https://tools.hmcts.net/jira/browse/RET-4043
```
[ ] Yes
[ ] No
```
=> RET-4043 remove duplicate getlogger import

src/main/controllers/ContactTheTribunalController.ts
=> Revert accordian

src/main/controllers/helpers/GeneralCorrespondenceHelper.ts, src/main/resources/locales/cy/translation/general-correspondence-notification-details.json, src/main/resources/locales/en/translation/general-correspondence-notification-details.json
https://tools.hmcts.net/jira/browse/RET-4057
```
[ ] Yes
[x] No
```
=> RET-4057 - add missed translation for document

src/main/controllers/helpers/FormHelpers.ts, src/main/definitions/api/caseApiResponse.ts, src/main/resources/locales/en/translation/hearing-document-upload.json
https://tools.hmcts.net/jira/browse/RET-3091
```
[ ] Yes
[ ] No
```
=> RET-3091 - update Scottish venue and document link for bundles

src/main/resources/locales/cy/translation/respondent-supporting-material.json
Small PR to add translation found missing whilst in test
```
[ ] Yes
[x] No
```
=> add missing translation on the supporting material page 

src/main/controllers/helpers/AllDocumentsHelper.ts, src/main/controllers/helpers/FormHelpers.ts, src/main/definitions/api/caseApiResponse.ts, src/main/definitions/constants.ts, src/main/helper/ApiFormatter.ts, src/main/services/CaseService.ts, src/test/unit/controller/helpers/FormHelper.test.ts, src/test/unit/helper/ApiFormatter.test.ts, src/test/unit/mocks/mockHearing.ts, src/test/unit/views/about-hearing-documents.test.ts
https://tools.hmcts.net/jira/browse/RET-3093
https://tools.hmcts.net/jira/browse/RET-4400
```
[ ] Yes
[ x] No
```
=> RET-4400 - update format of hearing label 

src/main/controllers/RespondentApplicationCYAController.ts, src/main/controllers/TribunalResponseCYAController.ts, src/main/controllers/helpers/RespondentApplicationCYAHelper.ts, src/main/resources/locales/cy/translation/respondent-application-cya.json, src/main/resources/locales/cy/translation/tribunal-response-cya.json, src/main/resources/locales/en/translation/respondent-application-cya.json, src/main/resources/locales/en/translation/tribunal-response-cya.json
https://tools.hmcts.net/jira/browse/RET-4535
Fix rule 92 answer not being translated on respond to application CYA page.
```
[ ] Yes
[X] No
```
=> RET-4535 - Fix translation

src/main/controllers/RespondentSupportingMaterialController.ts, src/main/controllers/helpers/RespondentSupportingMaterialHelper.ts, src/test/unit/controller/RespondentSupportingMaterialController.test.ts, src/test/unit/controller/helpers/RespondentSupportingMaterialHelper.test.ts
https://tools.hmcts.net/jira/browse/RET-4535
Fix Welsh language not persisting on navigation.
```
[ ] Yes
[X] No
```
=> RET-4535 - Fix Welsh navigation

src/main/views/citizen-hub-sidebar.njk
Set 'contact' sidebar width to prevent text wrapping.
```
[ ] Yes
[ ] No
```
=> Fix sidebar wrapping

src/main/views/citizen-hub-sidebar-3rd-width.njk, src/main/views/citizen-hub-sidebar.njk, src/main/views/judgment-details.njk, src/main/views/respondent-application-details.njk, src/main/views/tribunal-order-or-request-details.njk
=> Fix sidebar width

src/main/controllers/RespondentApplicationCYAController.ts, src/main/controllers/RespondentSupportingMaterialController.ts, src/main/controllers/TribunalRespondToOrderController.ts, src/main/controllers/TribunalResponseCYAController.ts, src/main/controllers/helpers/RespondentApplicationCYAHelper.ts, src/main/controllers/helpers/RespondentSupportingMaterialHelper.ts, src/main/resources/locales/cy/translation/respondent-application-cya.json, src/main/resources/locales/cy/translation/tribunal-response-cya.json, src/main/resources/locales/en/translation/respondent-application-cya.json, src/main/resources/locales/en/translation/tribunal-response-cya.json, src/main/views/judgment-details.njk, src/main/views/respondent-application-details.njk, src/main/views/tribunal-order-or-request-details.njk, src/test/unit/controller/RespondentSupportingMaterialController.test.ts, src/test/unit/controller/helpers/RespondentSupportingMaterialHelper.test.ts, src/test/unit/views/respondent-application-details.test.ts, yarn.lock
N/A
Merge master to Rule-92_New branch
```
[ ] Yes
[ ] No
```
=> Merge master to Rule-92_New branch

src/main/controllers/AttachmentController.ts, src/main/controllers/helpers/AllDocumentsHelper.ts, src/test/unit/controller/helpers/AllDocumentsHelper.test.ts
getSupportingMaterial support documents in respondCollection in SendNotificationTypeItem
```
[ ] Yes
[ ] No
```
=> RET-4062 getSupportingMaterial 

Dockerfile, README.md, charts/et-sya/Chart.yaml, charts/et-sya/values.yaml, config/default.json, config/development.json, docker-compose.yml, src/main/pcq/index.ts, src/test/a11y/a11y.ts, src/test/end-to-end/saucelabs.conf.js, src/test/smoke/smoke.conf.js, src/test/smoke/tests/healthCheck.test.js, src/test/unit/mocks/mockRequest.ts, src/test/unit/mocks/mockUrl.ts
N/A
Update port to 3002
```
[ ] Yes
[x] No
```
=> Update port to 3002

config/development.json
=> Update idam port

src/main/controllers/citizen-hub/CitizenHubDocumentController.ts, src/main/definitions/govuk/govukTable.ts, src/main/views/response-from-respondent-view.njk, src/test/unit/controller/citizen-hub/CitizenHubDocumentController.test.ts, src/test/unit/views/response-from-respondent-view.test.ts
https://tools.hmcts.net/jira/browse/RET-3271
EEC Notifications on ET3 Response page
```
[] Yes
[x] No
```
=> RET-3271: EEC Notifications on ET3 Response page

package.json, src/main/resources/locales/en/translation/respondent-details-check.json, yarn.lock
Fixing typo in certificate
```
[ ] Yes
[ ] No
```
=> Fixing typo

.github/PULL_REQUEST_TEMPLATE.md, src/main/controllers/RespondToTribunalResponseController.ts, src/main/controllers/RespondentSupportingMaterialController.ts, src/main/controllers/StoredToSubmitController.ts, src/main/controllers/TribunalRespondToOrderController.ts, src/main/controllers/helpers/ApplicationDetailsHelper.ts, src/main/controllers/helpers/ContactTheTribunalCYAHelper.ts, src/main/services/CaseService.ts, src/test/unit/controller/ContactTheTribunalSelectedController.test.ts, src/test/unit/controller/helpers/ApplicationDetailsHelper.test.ts, src/test/unit/controller/helpers/ContactTheTribunalCYAHelper.test.ts
Fix merge conflict updates for Rule-92 release branch
Revert PULL_REQUEST_TEMPLATE.md as master
For better view of Files changed, refer to #1232
```
[ ] Yes
[ ] No
```
=> Rule-92 Fix Merge

package.json, src/main/views/template.njk, yarn.lock
https://tools.hmcts.net/jira/browse/RET-4823
Adding JS for Dynatrace on AAT
```
[ ] Yes
[ ] No
```
=> Dynatrace RUM

Jenkinsfile_nightly
Fix nightly functional test step
```
[ ] Yes
[ ] No
```
=> Fix nightly functional test

src/main/views/template.njk
Add script to frontend to enable Dynatrace RUM
```
[ ] Yes
[X] No
```
=> Add Dynatrace monitoring in prod

src/main/controllers/RespondentSupportingMaterialController.ts, src/main/controllers/StoredToSubmitTribunalController.ts, src/main/controllers/helpers/AllDocumentsHelper.ts, src/main/controllers/helpers/DocumentHelpers.ts, src/main/controllers/helpers/StoredToSubmitHelpers.ts, src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
Fix merge conflicts after #1158 merged
Fix Document display issue for stored collection
```
[ ] Yes
[ ] No
```
=> Rule-92 v2 Fix merge conflicts

package.json, yarn.lock
=> Formidable CVE

src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
N/A 
Disable I.waitForVisible('#workAddressTypes', 240); in Functional Test
```
[ ] Yes
[x] No
```
=> Disable workAddressTypes Functional Test

src/main/assets/scss/main.scss, src/main/controllers/citizen-hub/CitizenHubController.ts, src/main/controllers/helpers/CitizenHubHelper.ts, src/main/controllers/helpers/multiples/MultiplePanelHelper.ts, src/main/definitions/api/caseApiResponse.ts, src/main/definitions/case.ts, src/main/definitions/constants.ts, src/main/definitions/multiples/multiplePanelData.ts, src/main/helper/ApiFormatter.ts, src/main/resources/locales/cy/translation/citizen-hub.json, src/main/resources/locales/en/translation/citizen-hub.json, src/main/resources/mocks/mockUserCaseWithCitizenHubLinks.ts, src/main/views/citizen-hub.njk, src/main/views/multiples/multiplePanel.njk, src/test/unit/controller/helpers/CitizenHubHelper.test.ts, src/test/unit/controller/helpers/multiples/MultiplePanelHelper.test.ts, src/test/unit/helper/ApiFormatter.test.ts, src/test/unit/mocks/mockUserCaseComplete.ts, src/test/unit/mocks/mockedApiData.ts, src/test/unit/views/citizen-hub.test.ts
https://tools.hmcts.net/jira/browse/RET-3823
Add panel for lead case view
```
[ ] Yes
[x] No
```
=> RET-3823 - Lead Case view

Jenkinsfile_nightly
Add OWASP Zap Scanner to nightly pipeline
```
[ ] Yes
[ ] No
```
=> Add Owasp Zap scanner

src/main/resources/locales/cy/translation/citizen-hub.json
https://tools.hmcts.net/jira/browse/RET-4981
Welsh translation for notification response 
```
[ ] Yes
[ x] No
```
=> CUI - Fix welsh translation for banner

src/main/definitions/constants.ts, src/main/definitions/postcode.ts, src/test/unit/controller/helpers/CaseHelpers.test.ts
https://tools.hmcts.net/jira/browse/RET-5208
Update ET1 Triage pages to include Newcastle office
```
[ ] Yes
[x] No
```
=> To be merged 17/06/2024 - RET-5208

src/main/modules/helmet/index.ts
Update CSPs around WebChat to stop Dynatrace errors
```
[ ] Yes
[ ] No
```
=> Update CSPs around Webchat to stop throwing errors

src/main/resources/locales/cy/translation/contact-the-tribunal-strike.json, src/main/resources/locales/cy/translation/contact-the-tribunal-vary.json, src/main/resources/locales/cy/translation/contact-the-tribunal-withdraw.json, src/main/resources/locales/en/translation/contact-the-tribunal-strike.json, src/main/resources/locales/en/translation/contact-the-tribunal-vary.json, src/main/resources/locales/en/translation/contact-the-tribunal-withdraw.json
https://tools.hmcts.net/jira/browse/RET-5540
Update references to ET Rules in external user portals
```
[ ] Yes
[x] No
```
=> To be merge on 6 Jan - RET-5540

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/DTSPO-23006
- Update nightly test run
- Added a new string parameter ALERT_FILTERS with a default value to configure alert filters for ZAP scan.
- Added a new string parameter CUSTOM_COOKIES to specify custom cookies for the ZAP scan.
**Does this PR introduce a breaking change?**
=> DTSPO-23006 add alert filters and custom cookies tests

Jenkinsfile_nightly
=> reset the zap filter library annotation

Jenkinsfile_nightly
Disable ZAP security scan 
```
[ ] Yes
[ ] No
```
=> disable zap security scan

src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
Enable a delay on the address lookup
```
[ ] Yes
[ ] No
```
=> Re-enable delay on waiting for work address

playwrighte2e/pages/employmentDetailsPage.ts, playwrighte2e/pages/personalDetailsPage.ts, src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
=> functional test fix

Jenkinsfile_CNP
Dean is set to work on the Perftest branch to implement some performance testing with Dynatrace integration into our pipelines. Change is to remove perftest from the synced branches so his changes are not overwritten
```
[ ] Yes
[ ] No
```
=> Removing perftest for Dean

Jenkinsfile_nightly
=> cookie-slack-detector-issue

charts/et-sya/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPO-24143
Update IDAM chart ref
```
[ ] Yes
[X] No
```
=> Use OCI repository instead of Helm

package.json, yarn.lock
Bump brace expansion to fix CVE
```
[ ] Yes
[ ] No
```
=> Bump brace expansion

src/test/java/build.gradle
Remove Jitpack reference from frontend
```
[ ] Yes
[ ] No
```
=> Update Fortify client dependency and change Maven repository URL

src/main/modules/helmet/index.ts
Update the CSP to include manifestSrc and govUk 5 change
```
[ ] Yes
[ ] No
```
=> Update CSP for Gov5 Changes

src/main/resources/locales/cy/translation/application-details.json, src/main/resources/locales/cy/translation/appoint-legal-representative.json, src/main/resources/locales/cy/translation/citizen-hub.json, src/main/resources/locales/cy/translation/contact-the-tribunal.json, src/main/resources/locales/cy/translation/your-applications.json
=> welsh translations noc
